In [1]:
%sql
SELECT * FROM transport_vic_dev.01_bronze.stops LIMIT 10;

DataFrame[stop_id: string, stop_name: string, stop_lat: string, stop_lon: string, stop_url: string, location_type: string, parent_station: string, wheelchair_boarding: string, level_id: string, feed_id: string, _source_file: string, _ingest_ts: timestamp, platform_code: string, stop_code: string]

In [ ]:
%sql
SELECT
    stop_id,
    stop_name,
    TRY_CAST(stop_lat AS FLOAT) AS stop_lat,
    TRY_CAST(stop_lon AS FLOAT) AS stop_lon,
    level_id,
    feed_id,
    _source_file,
    _ingest_ts,
    platform_code
FROM transport_vic_dev.01_bronze.stops LIMIT 10;

DataFrame[stop_id: string, stop_name: string, stop_lat: float, stop_lon: float, level_id: string, feed_id: string, _source_file: string, _ingest_ts: timestamp, platform_code: string]

In [3]:
%sql
SELECT * FROM transport_vic_dev.`02_silver`.stops LIMIT 10;

DataFrame[stop_id: string, stop_name: string, stop_lat: double, stop_lon: double, level_id: string, feed_id: string, platform_code: string, _source_file: string, _ingest_ts: timestamp, _silver_ingest_ts: timestamp]

In [9]:
%sql

SELECT * FROM transport_vic_dev.`02_silver`.stops WHERE stop_id = "20043"

DataFrame[stop_id: string, stop_name: string, stop_lat: double, stop_lon: double, level_id: string, feed_id: string, platform_code: string, _source_file: string, _ingest_ts: timestamp, _silver_ingest_ts: timestamp]

In [ ]:
%sql
SELECT *
FROM transport_vic_dev.`02_silver`.trip_updates t
LEFT JOIN transport_vic_dev.`02_silver`.stops s
ON t.stop_id = s.stop_id
WHERE t.stop_id = '20043'
ORDER BY t.entity_id, t.trip_id, t.start_date, t.start_time, t.stop_sequence;

DataFrame[feed_ts: timestamp, entity_id: string, trip_id: string, route_id: string, start_date: date, start_time: string, trip_rel: string, stop_sequence: int, stop_id: string, arrival_time: timestamp, arrival_delay_sec: int, departure_time: timestamp, departure_delay_sec: int, stop_rel: string, event_time: timestamp, source_file: string, _ingest_ts: timestamp, _silver_ts: timestamp, stop_id: string, stop_name: string, stop_lat: double, stop_lon: double, level_id: string, feed_id: string, platform_code: string, _source_file: string, _ingest_ts: timestamp, _silver_ingest_ts: timestamp]

In [14]:
%sql

WITH ordered AS (
  SELECT *,
    LAG(struct(arrival_time, arrival_delay_sec, departure_time,
               departure_delay_sec, stop_rel))
      OVER (PARTITION BY entity_id, stop_sequence ORDER BY feed_ts) AS prev
  FROM transport_vic_dev.`02_silver`.trip_updates
)
SELECT * EXCEPT(prev) FROM ordered
WHERE prev IS NULL
   OR struct(arrival_time, arrival_delay_sec, departure_time,
             departure_delay_sec, stop_rel) IS DISTINCT FROM prev;

DataFrame[feed_ts: timestamp, entity_id: string, trip_id: string, route_id: string, start_date: date, start_time: string, trip_rel: string, stop_sequence: int, stop_id: string, arrival_time: timestamp, arrival_delay_sec: int, departure_time: timestamp, departure_delay_sec: int, stop_rel: string, event_time: timestamp, source_file: string, _ingest_ts: timestamp, _silver_ts: timestamp]